# Generated by Django 4.1.7 on 2023-04-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=20)),
                ('heure', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=30)),
                ('autorisation', models.IntegerField(null=True)),
                ('serie', models.CharField(default='gen', max_length=3)),
                ('classe', models.IntegerField(default=1)),
                ('identifiant', models.CharField(default='eleve', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
                ('genre', models.CharField(default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UUID', models.CharField(max_length=20, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField(default=5)),
                ('month', models.IntegerField(default=1)),
                ('day', models.IntegerField(default=1)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.student')),
                ('slot', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.slot')),
                ('students', models.ManyToManyField(related_name='class_student', to='login.student')),
            ],
        ),
    ]
