# Generated by Django 4.1.7 on 2023-04-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='serie',
            field=models.CharField(default='gen', max_length=3),
        ),
    ]
