# Generated by Django 4.1.7 on 2023-04-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='identifiant',
            field=models.CharField(default='eleve', max_length=128),
        ),
    ]
