# Generated by Django 4.1.7 on 2023-04-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='identifiant',
            field=models.CharField(default='eleve', max_length=20),
        ),
    ]
